on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    env:
      LT_USERNAME: "naveda"  # Set your desired environment variable here
      LT_ACCESS_KEY: "Y38l1pghEBmUKFqfk5XZSPrwP9Tc2cU8eWNaBPZjRYpXhYerxb"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
          echo "Hello"
          cd web_io
          npm install selenium-webdriver 
          npm install webdriverio
          npm i
          npm install
          npm i wdio-lambdatest-service --save-dev
          npm run single
